-- USING POSTGRES;
-- CREAR BASE DE DATOS
DROP DATABASE IF EXISTS BASEDEDATOS;
CREATE DATABASE BASEDEDATOS;
-- CREAR TABLA
CREATE TABLE PERSONA(
	ID_PERSONA INT NOT NULL ,
	-- ID_PERSONA SERIAL PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20),
	DNI VARCHAR(10),
	--PRIMARY (KEY ID_PERSONA)
);
-- INSERTAR REGISTROS
INSERT INTO PERSONA VALUES (0,'KEVIN','75862365');
INSERT INTO PERSONA (ID_PERSONA, NOMBRE, DNI) VALUES
(1,'ANA','87965482'),
(2,'PAUL','12547896');

-- UPDATE
UPDATE PERSONA SET DNI = '12345678' WHERE DNI = '12547896';

-- CONSULTAS
SELECT * FROM PERSONA;

SELECT (ID_PERSONA*2) AS DOBLE_ID FROM PERSONA;

SELECT * FROM PERSONA WHERE ID_PERSONA != 1;

SELECT * FROM PERSONA WHERE ID_PERSONA >= 1 AND NOMBRE = 'ANA';

-- ELIMINAR DATOS
/*
DELETE FROM PERSONA WHERE NOMBRE = 'PAUL'
*/

-- MODIFICAR CON ALTER
-- AGREGAR UNA COLUMNA
ALTER TABLE PERSONA
ADD COLUMN TEST VARCHAR(20);
-- CAMBIAR DE NOMBRE A UNA COLUMNA
ALTER TABLE PERSONA
RENAME COLUMN TEST TO TEST2;
-- ELIMINAR UNA COLUMNA
ALTER TABLE PERSONA
DROP COLUMN TEST2;

-- MODIFICAR UNA COLUMNA
-- AGREGAR UNA COLUMNA NO NULA
ALTER TABLE PERSONA
ADD COLUMN TEST VARCHAR(20);
UPDATE PERSONA SET TEST = 'PRUEBA'

ALTER TABLE PERSONA
ALTER COLUMN TEST SET NOT NULL;
-- PERMITIR VALORES NULOS
ALTER TABLE PERSONA
ALTER COLUMN TEST DROP NOT NULL;

-- CAMBIAR EL TIPO DE DATO EN UNA COLUMNA
ALTER TABLE PERSONA
ALTER COLUMN TEST TYPE VARCHAR(10);
SELECT * FROM PERSONA;

-- ESTABLECER CLAVES PRIMARIAS
ALTER TABLE PERSONA 
ADD PRIMARY KEY (ID_PERSONA)
INSERT INTO PERSONA VALUES (0,'KEVIN','75862365');

-- AUTO INCREMENTAR

CREATE TABLE ANIMAL(
	ID_ANIMAL SERIAL PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20)
);
INSERT INTO ANIMAL (NOMBRE) VALUES 
('ZEBRA'),
('LEON');
SELECT * FROM ANIMAL;

-- ELIMINAR ALGUNOS DATOS EN TABLA SI LA ACOMPAÑAMOS DE LA CLAUSUAL WHERE
DELETE FROM ANIMAL;
-- ELIMINAR TABLA
DROP TABLE ANIMAL;
-- TRUNCATE, ELIMINA TODOS LOS DATOS EN TABLA
TRUNCATE TABLE ANIMAL;
-- REINICIAR EL CONTADOR A CERO
TRUNCATE TABLE ANIMAL RESTART IDENTITY;
-- VALORES POR DEFAULT
DROP TABLE ANIMAL;
CREATE TABLE ANIMAL(
	ID_ANIMAL SERIAL PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20),
	TIPO VARCHAR(20) DEFAULT 'DESCONOCIDO'
);
INSERT INTO ANIMAL (NOMBRE) VALUES 
('ZEBRA'),
('LEON');
SELECT * FROM ANIMAL;

-- COLUMNAS CALCULADAS
SELECT (ID_PERSONA*2) AS DOBLE_ID FROM PERSONA;

-- ORDER BY
SELECT * FROM PERSONA ORDER BY DNI DESC;
SELECT * FROM PERSONA ORDER BY 3 DESC;
--  LIKE
SELECT * FROM ANIMAL WHERE NOMBRE LIKE '%EB%';
-- COUNT 
ALTER TABLE PERSONA
ADD COLUMN GENERO VARCHAR(20);
SELECT *FROM PERSONA 
UPDATE PERSONA SET GENERO = 'MASCULINO' WHERE NOMBRE LIKE 'PAUL' OR NOMBRE LIKE 'KEVIN';
UPDATE PERSONA SET GENERO = 'FEMENINO' WHERE NOMBRE LIKE 'ANA';

SELECT COUNT(*) AS CANTIDAD, GENERO FROM PERSONA GROUP BY GENERO;

-- SUM
SELECT SUM(ID_PERSONA) AS SUMA FROM PERSONA; 

-- FUNCIONES
SELECT MIN(ID_PERSONA) AS MINIMO, GENERO FROM PERSONA GROUP BY GENERO;
SELECT MAX(ID_PERSONA) AS MINIMO, GENERO FROM PERSONA GROUP BY GENERO;
SELECT AVG(ID_PERSONA) AS MINIMO, GENERO FROM PERSONA GROUP BY GENERO;
-- HAVING
SELECT AVG(ID_PERSONA) AS MINIMO, GENERO FROM PERSONA GROUP BY GENERO HAVING GENERO LIKE 'F%';
-- DISTINCT
SELECT DISTINCT GENERO FROM PERSONA;
-- BETWEEN
SELECT *FROM PERSONA WHERE ID_PERSONA BETWEEN 1 AND 2;
-- RESTRICCION
ALTER TABLE PERSONA ADD CONSTRAINT UQ_NOMBRE UNIQUE (NOMBRE);
INSERT INTO PERSONA VALUES (4,'KAMILA','75412365');
UPDATE PERSONA  SET TEST = 'PRUEBA', GENERO = 'FEMENINO' WHERE NOMBRE LIKE 'KAMILA'
SELECT *FROM PERSONA;
-- ELIMINAR EL CONSTRAINT
ALTER TABLE PERSONA DROP CONSTRAINT UQ_NOMBRE;
-- RELACIONAR TABLAS
SELECT * FROM ANIMAL;
CREATE TABLE CONTINENTE(
	COD_CONTINENTE INT PRIMARY KEY,
	NOMBRE VARCHAR(10)
);
INSERT INTO CONTINENTE VALUES
(1,'AMERICA'),
(2,'ASIA'),
(3,'EUROPA'),
(4,'AFRICA');
SELECT *FROM CONTINENTE;
ALTER TABLE ANIMAL ADD COD_CONTINENTE INT;
ALTER TABLE ANIMAL ADD CONSTRAINT FKTEST
FOREIGN KEY (COD_CONTINENTE) REFERENCES CONTINENTE(COD_CONTINENTE);
SELECT *FROM ANIMAL;
UPDATE ANIMAL SET COD_CONTINENTE = 4;
-- CREAR FUNCIONES
CREATE OR REPLACE FUNCTION SUMA(N1 INT, N2 INT) RETURNS INTEGER
AS
$$
SELECT N1+N2;
$$
LANGUAGE SQL

SELECT SUMA(1,5);

CREATE FUNCTION BUSCAR(VARCHAR) RETURNS INTEGER
AS
$$
SELECT ID_PERSONA FROM PERSONA WHERE NOMBRE LIKE $1;
$$
LANGUAGE SQL
-- DROP FUNCTION BUSCAR
SELECT BUSCAR('ANA');
-- FUNCIONES SIN RETORNO
CREATE FUNCTION INSETAR_ANIMAL() RETURNS VOID
AS
$$
INSERT INTO ANIMAL (NOMBRE) VALUES 
('MONO'),
('PATO');
$$
LANGUAGE SQL
SELECT INSETAR_ANIMAL();
SELECT *FROM ANIMAL;
-- LIMIT 
SELECT * FROM ANIMAL LIMIT 2;

-- DISPARADORES
SELECT *FROM ANIMAL;
CREATE TABLE LOG_TRIGGERS(
	ID_ANIMAL INT,
	NOMBRE VARCHAR(20)
);
CREATE FUNCTION TR_AA() RETURNS TRIGGER
AS
$$
BEGIN 
INSERT INTO LOG_TRIGGERS VALUES (OLD.ID_ANIMAL, OLD.NOMBRE);
RETURN NEW;
END
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER TR_UPDATE BEFORE UPDATE ON ANIMAL
FOR EACH ROW
EXECUTE PROCEDURE TR_AA();

UPDATE ANIMAL SET COD_CONTINENTE = 3 WHERE NOMBRE LIKE 'MONO';
SELECT * FROM LOG_TRIGGERS;

-- CON LA CLUSULA AFTER

CREATE TABLE TBL2(
	ID_ANIMAL INT,
	NOMBRE VARCHAR(20),
	FECHA DATE
);
CREATE FUNCTION TR_AB() RETURNS TRIGGER
AS
$$
DECLARE
FECHA DATE := CURRENT_DATE;
BEGIN
INSERT INTO TBL2 VALUES (NEW.ID_ANIMAL, NEW.NOMBRE,FECHA);
RETURN NEW;
END
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER TR_INSTERT AFTER INSERT ON ANIMAL
FOR EACH ROW
EXECUTE PROCEDURE TR_AB();
INSERT INTO ANIMAL VALUES(10,'COBRA',2);
SELECT *FROM ANIMAL;
SELECT *FROM TBL2;
-- CLAUSULA IN
SELECT *FROM ANIMAL WHERE COD_CONTINENTE IN (2,3);
-- LIMIT Y OFFSET
SELECT * FROM ANIMAL LIMIT 5 OFFSET 2;
-- CREAR VISTA(VIEW)
CREATE VIEW VIEW_DATA_ANIMAL AS SELECT *FROM ANIMAL;--WHERE ;
SELECT *FROM VIEW_DATA_ANIMAL;
-- UNION DEBEN SER DEL MISMO TIPO DE DATO LAS TABLAS
SELECT *FROM ANIMAL UNION SELECT *FROM VIEW_DATA_ANIMAL 
		-- PARA ESTE CASO SALE LO MISMO YA QUE LAS DOS TBL SON IGUALES(MISMAS FILAS)
-- INNER JOIN
SELECT *FROM ANIMAL INNER JOIN CONTINENTE ON ANIMAL.COD_CONTINENTE = CONTINENTE.COD_CONTINENTE 
-- LEFT JOIN
SELECT *FROM CONTINENTE  LEFT JOIN ANIMAL  ON ANIMAL.COD_CONTINENTE = CONTINENTE.COD_CONTINENTE
-- RIGHT JOIN
SELECT *FROM ANIMAL   RIGHT JOIN CONTINENTE  ON ANIMAL.COD_CONTINENTE = CONTINENTE.COD_CONTINENTE 
-- FULL JOIN
SELECT *FROM ANIMAL FULL JOIN CONTINENTE  ON ANIMAL.COD_CONTINENTE = CONTINENTE.COD_CONTINENTE
-- CROSS JOIN
SELECT *FROM ANIMAL CROSS JOIN CONTINENTE
-- VISTAS
CREATE VIEW VIEW_ANIMAL AS SELECT *FROM ANIMAL WHERE COD_CONTINENTE=4 WITH CHECK OPTION;
SELECT *FROM VIEW_ANIMAL;
-- FUNCIONES MATEMATICAS
SELECT ABS(COD_CONTINENTE) FROM ANIMAL;
SELECT CBRT(COD_CONTINENTE) FROM ANIMAL; -- RAIZ CUBICA
SELECT CEILING(COD_CONTINENTE) FROM ANIMAL; --REDONDEO HACIA ARRIBA
SELECT FLOOR(COD_CONTINENTE) FROM ANIMAL; -- REDONDEO HACIA ABAJO
SELECT POWER(COD_CONTINENTE,2) FROM ANIMAL; -- POTENCIA
SELECT ROUND(COD_CONTINENTE,5) FROM ANIMAL;
SELECT SIGN(COD_CONTINENTE) FROM ANIMAL;
SELECT SQRT(COD_CONTINENTE) FROM ANIMAL; -- RAIZ CUADRADA
SELECT MOD(COD_CONTINENTE,6) FROM ANIMAL;  -- MODULO
SELECT PI();
SELECT RANDOM();
SELECT TRUNC(-57.456,2);
-- MANEJO DE CARACTERES
SELECT CHAR_LENGTH('HOLA MUNDO');
SELECT UPPER('Hola MUNDO');
SELECT LOWER('Hola MUNDO');
SELECT POSITION('MUNDO' IN 'Hola MUNDO');
SELECT SUBSTRING('Hola MUNDO' FROM 2 FOR 6);
SELECT TRIM('  Hola MUNDO            ');
SELECT TRIM(LEADING '-' FROM '---Hola MUNDO--');
SELECT TRIM(TRAILING '-' FROM '---Hola MUNDO--');
SELECT TRIM(BOTH '-' FROM '---Hola MUNDO--');
SELECT SUBSTR('Hola MUNDO',5,8);
-- FECHAS Y TIEMPO
SELECT CURRENT_DATE;
SELECT CURRENT_TIME;
SELECT CURRENT_TIMESTAMP;
SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
-- CONTROLAR VALORES NULOS
SELECT * FROM ANIMAL WHERE COD_CONTINENTE IS NULL;
SELECT * FROM ANIMAL WHERE COD_CONTINENTE IS NOT NULL;
-- SECUENCIAS
CREATE SEQUENCE SEC_INDICE
START WITH 1
INCREMENT BY 20
MINVALUE 1
MAXVALUE 100
RESTART 10
CYCLE; -- ESTA LINEA SE PUEDE OMITIR SI NO QUIERES CICLO
SELECT *FROM SEC_INDICE;
SELECT  NEXTVAL('SEC_INDICE');
DROP SEQUENCE SEC_INDICE;

-- VARIABLES
DO $$
DECLARE X INT := 10;
		Y INT := 10;
		Z INT;
BEGIN
	Z := X*Y;
	RAISE NOTICE 'RESULTADO: %', Z;
END $$;

DO $$
BEGIN
	IF EXISTS(SELECT NOMBRE FROM ANIMAL WHERE NOMBRE LIKE 'MONO') THEN
		RAISE NOTICE 'ENCONTRADO';
	END IF;
END $$;

DO $$
DECLARE X INT := 10;
		Y INT := 0;
BEGIN
	WHILE(Y<X)
	LOOP
	Y := Y+1;
	RAISE NOTICE 'AVANZAR';
	END LOOP;
END $$;
-- CURSOR
DO $$
DECLARE 
	REGISTRO RECORD;
	CURSOR_NOMBRE CURSOR FOR SELECT * FROM ANIMAL; 
BEGIN
OPEN CURSOR_NOMBRE;
FETCH CURSOR_NOMBRE INTO REGISTRO;
RAISE NOTICE 'NOMBRE: %',REGISTRO.NOMBRE;
END $$
LANGUAGE PLPGSQL;

-- CURSOR CON BUCLE

DO $$
DECLARE 
	REGISTRO RECORD;
	CURSOR_NOMBRE CURSOR FOR SELECT * FROM ANIMAL; 
BEGIN
OPEN CURSOR_NOMBRE;
FETCH CURSOR_NOMBRE INTO REGISTRO;
WHILE (FOUND) LOOP
RAISE NOTICE 'NOMBRE: %',REGISTRO.NOMBRE;
FETCH CURSOR_NOMBRE INTO REGISTRO;
END LOOP;
END $$
LANGUAGE PLPGSQL;

DO $$
DECLARE 
	REGISTRO RECORD;
	CURSOR_NOMBRE CURSOR FOR SELECT * FROM ANIMAL; 
BEGIN
FOR REGISTRO IN CURSOR_NOMBRE LOOP
RAISE NOTICE 'NOMBRE: %',REGISTRO.NOMBRE;
END LOOP;
END $$
LANGUAGE PLPGSQL;

